name: storypad
version: 2.10.0+329
publish_to: none
environment:
  sdk: ^3.5.4
description: Minimalist application to write stories, notes, diary!

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_dialog: ^2.4.1
  animated_clipper: ^0.2.0+2
  animations: ^2.0.11
  audio_service: ^0.18.18
  cached_network_image: ^3.4.1
  copy_with_extension: ^6.0.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.3.3
  dismissible_page: ^1.0.2
  dynamic_color: ^1.7.0
  easy_localization: ^3.0.7+1
  file_picker: ^10.1.2
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_remote_config: ^5.4.3
  firebase_storage: ^12.4.5
  flutter_custom_tabs: ^2.3.0
  flutter_markdown: ^0.7.7
  flutter_native_splash: ^2.4.6
  flutter_quill: 11.0.0
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_slidable: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.1.0
  fuzzy: ^0.5.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  googleapis: ^14.0.0
  html_character_entities: ^1.0.0+1
  in_app_review: ^2.0.10
  in_app_update: ^4.2.3
  json_annotation: ^4.9.0
  json_serializable: 6.9.0
  just_audio: ^0.10.0
  local_auth: ^2.3.0
  material_design_icons_flutter: ^7.0.7296
  objectbox: ^4.2.0
  objectbox_flutter_libs: any
  package_info_plus: ^8.3.0
  photo_view: ^0.15.0
  provider: ^6.1.4
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.14
  copy_with_extension_gen: ^6.0.0
  csv: ^6.0.0
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/firestore_storage_map.json
    - translations/
    - assets/images/
    - assets/images/onboarding/
    - assets/emoji-64/
