name: storypad
version: 2.20.0+500
publish_to: none
environment:
  sdk: ^3.8.0
description: Minimalist application to write stories, notes, diary!

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_dialog:
    path: packages/adaptive_dialog
  animated_clipper: ^0.2.0+2
  animations: ^2.0.11
  audio_service: ^0.18.18
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.2
  copy_with_extension: ^10.0.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.1.0
  dismissible_page: ^1.0.2
  dynamic_color: ^1.8.1
  easy_localization: ^3.0.7+1
  file_picker: ^10.1.9
  firebase_analytics: ^12.0.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.1
  firebase_remote_config: ^6.0.0
  firebase_storage: ^13.0.0
  flutter_custom_tabs: ^2.3.0
  flutter_markdown: ^0.7.7
  flutter_native_splash: ^2.4.6
  flutter_quill:
    git:
      url: https://github.com/theachoem/flutter-quill.git
      ref: 6f4f645ad6d3a5d0759ab3b52177a33162e452c9
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_slidable: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.1.0
  fuzzy: ^0.5.1
  google_fonts: ^6.2.1
  google_sign_in: ^7.2.0
  googleapis: ^15.0.0
  html_character_entities: ^1.0.0+1
  in_app_review: ^2.0.10
  in_app_update: ^4.2.3
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  just_audio: ^0.10.4
  local_auth: ^3.0.0
  material_design_icons_flutter: ^7.0.7296
  objectbox: ^5.0.0
  objectbox_flutter_libs: any
  package_info_plus: ^9.0.0
  photo_view: ^0.15.0
  provider: ^6.1.4
  record: ^6.1.2
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  visibility_detector: ^0.4.0+2
  purchases_flutter: ^9.6.1
  image_picker: ^1.1.2
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.15
  copy_with_extension_gen: ^10.0.1
  csv: ^6.0.0
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/firestore_storage_map.json
    - translations/
    - templates/
    - assets/images/
    - assets/images/onboarding/
    - assets/emoji-64/
