# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: StoryPad - Story & Diary
description: >-
  A minimalist app that inspires you to write stories and diaries with ease and simplicity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://storypad.juniorise.com" # the base hostname & protocol for your site, e.g. http://example.com

logo: assets/logo.png
favicon_ico: assets/favicon_io/favicon.ico

aux_links:
  "Source Code":
    - "https://github.com/theachoem/storypad"
aux_links_new_tab: true

color_scheme: dark

# Build settings
# theme: minima
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

footer_content: 'Copyright &copy;2021-2025 Juniorise. Distributed by a <a href="https://github.com/theachoem/storypad/blob/develop/LICENSE">GNU GENERAL PUBLIC LICENSE.</a>'
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
